AWSTemplateFormatVersion: '2010-09-09'
Description: cfn-index-photos & cfn-search-photos Lambda functions

Parameters:
  ESDomainEndpoint:
    Type: String
    Description: HTTPS endpoint of your existing OpenSearch domain
  IndexLambdaRoleArn:
    Type: String
    Description: ARN of the Index-Photos Lambda execution role
  SearchLambdaRoleArn:
    Type: String
    Description: ARN of the Search-Photos Lambda execution role

Resources:

  cfnIndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cfn-index-photos
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !Ref IndexLambdaRoleArn
      Timeout: 10
      MemorySize: 128
      Layers:
        - arn:aws:lambda:us-east-1:202533503880:layer:LF2_Requests:2
      Environment:
        Variables:
          REGION:      us-east-1
          ES_ENDPOINT: !Ref ESDomainEndpoint
          ES_INDEX:    photos
          ES_USERNAME: photo-album
          ES_PASSWORD: Cloud12345@
      Code:
        ZipFile: |
          import os
          import json
          import boto3
          import datetime
          import requests
          from requests.auth import HTTPBasicAuth

          # Environment Variables
          REGION = os.environ['REGION']
          ES_ENDPOINT = os.environ['ES_ENDPOINT']
          ES_USERNAME = os.environ['ES_USERNAME']
          ES_PASSWORD = os.environ['ES_PASSWORD']
          ES_INDEX = os.environ['ES_INDEX']

          # AWS clients
          rek = boto3.client('rekognition', region_name=REGION)
          s3  = boto3.client('s3', region_name=REGION)

          def lambda_handler(event, context):
              # Parse out the S3 Bucket name and Image name. 
              rec = event['Records'][0]['s3']
              bucket = rec['bucket']['name']
              key = rec['object']['key']

              # Detect labels in the image, using AWS Rekognition ("detect_labels" method). 
              rek_resp = rek.detect_labels(
                  Image={'S3Object':{'Bucket':bucket,'Name':key}},
              )
              detected = [lbl['Name'] for lbl in rek_resp['Labels']]

              # Use the S3 SDK's "head_object" method to retrieve the "x-amz-meta-customLabels" metadata field, if applicable. 
              head = s3.head_object(Bucket=bucket, Key=key)
              meta = head.get('Metadata', {})
              custom = meta.get('customlabels', '')
              custom_labels = [c.strip() for c in custom.split(',') if c.strip()]

              # Merge the labels detected by Rekognition with the custom labels provided by the user. 
              labels = list({*custom_labels, *detected})

              # Build the JSON document to be stored in an OpenSearch index ("photos"). 
              doc = {
                  "objectKey":        key,
                  "bucket":           bucket,
                  "createdTimestamp": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
                  "labels":           labels
              }

              # Store the JSON document to OpenSearch Index via HTTP POST request
              url = f"{ES_ENDPOINT}/{ES_INDEX}/_doc"
              headers = {"Content-Type": "application/json"}
              auth = HTTPBasicAuth(ES_USERNAME, ES_PASSWORD)
              resp = requests.post(url, auth=auth, headers=headers, data=json.dumps(doc))
              if resp.status_code not in (200, 201):
                  print(f"Elasticsearch error [{resp.status_code}]: {resp.text}")
                  raise Exception(f"Indexing failed: {resp.status_code}")

              print(f"Indexed {key}: {labels}")
              return {
                  "statusCode": resp.status_code,
                  "body":       json.dumps({"indexed": key})
              }

  cfnIndexPhotosVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref cfnIndexPhotosFunction 

  cfnIndexPhotosProdAlias:
    Type: AWS::Lambda::Alias
    Properties: 
      Name: PROD
      FunctionName: !Ref cfnIndexPhotosFunction
      FunctionVersion: !GetAtt cfnIndexPhotosVersion.Version

  cfnSearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cfn-search-photos
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !Ref SearchLambdaRoleArn
      Timeout: 10
      MemorySize: 128
      Layers:
        - arn:aws:lambda:us-east-1:202533503880:layer:LF2_Requests:2
      Environment:
        Variables:
          REGION:       us-east-1
          ES_ENDPOINT:  !Ref ESDomainEndpoint
          ES_INDEX:     photos
          ES_USERNAME:  photo-album
          ES_PASSWORD:  Cloud12345@
          BOT_ID:       ULVNLPMC5B
          BOT_ALIAS_ID: TSTALIASID
          LOCALE_ID:    en_US
      Code:
        ZipFile: |
          import os
          import json
          import boto3
          import requests
          from requests.auth import HTTPBasicAuth

          # Environment Variables
          REGION = os.environ['REGION']
          ES_ENDPOINT = os.environ['ES_ENDPOINT']
          ES_USERNAME = os.environ['ES_USERNAME']
          ES_PASSWORD = os.environ['ES_PASSWORD']
          ES_INDEX = os.environ['ES_INDEX']
          LEX_BOT_ID = os.environ['BOT_ID']
          LEX_ALIAS_ID = os.environ['BOT_ALIAS_ID']
          LEX_LOCALE = os.environ['LOCALE_ID']

          # AWS clients
          lex_client = boto3.client('lexv2-runtime', region_name=REGION)
          s3_client = boto3.client('s3', region_name=REGION)

          def lambda_handler(event, context):
              # Extract the user query. 
              params = event.get('queryStringParameters') or {}
              q = params.get('q','').strip()

              # If the user did not enter a query, return an empty list. 
              if not q:
                  return {
                      "statusCode": 200,
                      "headers": {
                          "Content-Type": "application/json",
                          "Access-Control-Allow-Origin": "*"
                      },
                      "body": json.dumps({"results":[]})
                  }

              # Disambiguate the user query using the AWS Lex bot. 
              lex_resp = lex_client.recognize_text(
                  botId        = LEX_BOT_ID,
                  botAliasId   = LEX_ALIAS_ID,
                  localeId     = LEX_LOCALE,
                  sessionId    = context.aws_request_id,
                  text         = q
              )
              slots = lex_resp.get('sessionState',{}).get('intent',{}).get('slots',{})

              # Extract the "query1" and "query2" slots from the Lex response. 
              terms = []

              # "query1" is a required slot. 
              q1_slot = slots.get('query1')
              if q1_slot and q1_slot.get('value') and q1_slot['value'].get('interpretedValue'):
                  terms.append(q1_slot['value']['interpretedValue'])

              # "query2" is an optional slot. 
              q2_slot = slots.get('query2')
              if q2_slot and q2_slot.get('value') and q2_slot['value'].get('interpretedValue'):
                  terms.append(q2_slot['value']['interpretedValue'])

              # If the user query is not a SearchIntent, return an empty list. 
              if not terms:
                  return {
                      "statusCode": 200,
                      "headers": {
                          "Content-Type": "application/json",
                          "Access-Control-Allow-Origin": "*"
                      },
                      "body": json.dumps({"results":[]})
                  }

              # Construct the OpenSearch query. 
              should_clauses = []

              should_clauses.append({
                  "match": {
                      "labels": {
                          "query": terms[0],
                          "fuzziness": "AUTO"
                      }
                  }
              })

              if len(terms) > 1:
                  should_clauses.append({
                      "match": {
                          "labels": {
                              "query": terms[1],
                              "fuzziness": "AUTO"
                          }
                      }
                  })

              es_body = {
                  "query": {
                      "bool": {
                          "should": should_clauses,
                          "minimum_should_match": 1
                      }
                  }
              }

              # Search the "photos" OpenSearch index for results via the HTTP GET request. 
              url = f"{ES_ENDPOINT}/{ES_INDEX}/_search"
              resp = requests.get(
                  url,
                  auth=HTTPBasicAuth(ES_USERNAME, ES_PASSWORD),
                  headers={"Content-Type":"application/json"},
                  data=json.dumps(es_body)
              )
              resp.raise_for_status()
              hits = resp.json().get('hits',{}).get('hits',[])

              # Format the result based on the API spec. 
              results = []
              for h in hits:
                  src = h.get('_source',{})
                  # Construct the S3 Object URL for the image. 
                  url = f"https://{src['bucket']}.s3.amazonaws.com/{src['objectKey']}"
                  results.append({
                      "url":    url,
                      "labels": src.get('labels',[])
                  })

              return {
                  "statusCode": 200,
                  "headers": {
                      "Content-Type": "application/json",
                      "Access-Control-Allow-Origin": "*"    # if you need CORS
                  },
                  "body": json.dumps({"results": results})
              }

  cfnSearchPhotosVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref cfnSearchPhotosFunction

  cfnSearchPhotosProdAlias:
    Type: AWS::Lambda::Alias
    Properties:
      Name: PROD
      FunctionName: !Ref cfnSearchPhotosFunction
      FunctionVersion: !GetAtt cfnSearchPhotosVersion.Version

Outputs:
  IndexFunctionArn:
    Description: ARN of the index-photos function
    Value: !GetAtt cfnIndexPhotosFunction.Arn
    Export:
      Name: cfn-PhotoAlbum-IndexFunctionArn

  SearchFunctionArn:
    Description: ARN of the search-photos function
    Value: !GetAtt cfnSearchPhotosFunction.Arn
    Export:
      Name: cfn-PhotoAlbum-SearchFunctionArn