AWSTemplateFormatVersion: '2010-09-09'
Description: "Lambda invoke permissions for S3 & API"

Parameters:
  cfnApiId:
    Type: String
    Description: API Gateway ID (from api-gateway.yaml)

Resources:
  cfnPermissionIndexFromS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue cfn-PhotoAlbum-IndexFunctionArn
      Action:       lambda:InvokeFunction
      Principal:    s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${cfn-PhotoAlbum-PhotoBucketName}

  cfnPermissionSearchFromApi:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue cfn-PhotoAlbum-SearchFunctionArn
      Action:       lambda:InvokeFunction
      Principal:    apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${cfnApiId}/*/GET/search