AWSTemplateFormatVersion: '2010-09-09'
Description: CFN parameter file for PhotoAlbum.

Parameters:
  ESDomainEndpoint:
    Type: String
    Description: HTTPS endpoint of your existing OpenSearch domain
    Default: "https://search-photos-phn4iwyba5uyzwsh24i3ayvmxy.us-east-1.es.amazonaws.com"

  ESDomainArn:
    Type: String
    Description: ARN of your existing OpenSearch domain (including /*)
    Default: "arn:aws:es:us-east-1:202533503880:domain/photos/*"

Resources:
  NoOp:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  ExportESDomainEndpoint:
    Description: Exported OpenSearch endpoint
    Value: !Ref ESDomainEndpoint
    Export:
      Name: cfn-PhotoAlbum-ESDomainEndpoint

  ExportESDomainArn:
    Description: Exported OpenSearch ARN
    Value: !Ref ESDomainArn
    Export:
      Name: cfn-PhotoAlbum-ESDomainArn